CREATE TABLE AUTOR (
  idAUTOR INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Nome TEXT NULL,
  PRIMARY KEY(idAUTOR)
);

CREATE TABLE AUTOR_has_EDITORA (
  AUTOR_idAUTOR INTEGER UNSIGNED NOT NULL,
  EDITORA_idEDITORA INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(AUTOR_idAUTOR, EDITORA_idEDITORA),
  INDEX AUTOR_has_EDITORA_FKIndex1(AUTOR_idAUTOR),
  INDEX AUTOR_has_EDITORA_FKIndex2(EDITORA_idEDITORA)
);

CREATE TABLE AUTOR_has_LIVRO (
  AUTOR_idAUTOR INTEGER UNSIGNED NOT NULL,
  LIVRO_idLIVRO INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(AUTOR_idAUTOR, LIVRO_idLIVRO),
  INDEX AUTOR_has_LIVRO_FKIndex1(AUTOR_idAUTOR),
  INDEX AUTOR_has_LIVRO_FKIndex2(LIVRO_idLIVRO)
);

CREATE TABLE EDITORA (
  idEDITORA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Nome TEXT NOT NULL,
  PRIMARY KEY(idEDITORA)
);

CREATE TABLE LIVRO (
  idLIVRO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  USUARIO_idUSUARIO INTEGER UNSIGNED NOT NULL,
  EDITORA_idEDITORA INTEGER UNSIGNED NOT NULL,
  Nome TEXT NULL,
  PRIMARY KEY(idLIVRO),
  INDEX LIVRO_FKIndex1(EDITORA_idEDITORA),
  INDEX LIVRO_FKIndex2(USUARIO_idUSUARIO)
);

CREATE TABLE USUARIO (
  idUSUARIO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Nome TEXT NULL,
  Matricula INTEGER UNSIGNED NULL,
  PRIMARY KEY(idUSUARIO)
);
